/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import model.inventory.Inventory;
import model.inventory.InventoryDAOImp;
/**
 *
 * @author nikethanann
 */
public class AddInventoryMedicine extends javax.swing.JPanel {

    JSplitPane jSplitPane;
    public AddInventoryMedicine(JSplitPane jSplitPane, Inventory inv) {
        initComponents();
        this.jSplitPane = jSplitPane;
        if(!inv.getMedicineID().isEmpty()){
            medicineIDTxtField.setText(inv.getMedicineID());
            medicineNameTxtField.setText(inv.getMedicineName());
            qtyTxtField.setText(Integer.toString(inv.getQuantity()));
            dosageTxtField.setText(inv.getDosage());
            priceTxtField.setText(Float.toString(inv.getPrice()));
            commTxtField.setText(inv.getComm());
            storeIDTxtField.setText(inv.getStoreID());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicineTitle = new javax.swing.JLabel();
        medicineIDLbl = new javax.swing.JLabel();
        medicineIDTxtField = new javax.swing.JTextField();
        medicineNameLbl = new javax.swing.JLabel();
        medicineNameTxtField = new javax.swing.JTextField();
        qtyLbl = new javax.swing.JLabel();
        qtyTxtField = new javax.swing.JTextField();
        dosageLbl = new javax.swing.JLabel();
        dosageTxtField = new javax.swing.JTextField();
        commLbl = new javax.swing.JLabel();
        commTxtField = new javax.swing.JTextField();
        storeIDLbl = new javax.swing.JLabel();
        storeIDTxtField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        priceLbl = new javax.swing.JLabel();
        priceTxtField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        medErrorLbl = new javax.swing.JLabel();
        medName = new javax.swing.JLabel();
        qtyErrorLbl = new javax.swing.JLabel();
        doseErrorLbl = new javax.swing.JLabel();
        commErrorLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        priceErrorLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(160, 213, 229));

        medicineTitle.setFont(new java.awt.Font("PT Sans", 1, 24)); // NOI18N
        medicineTitle.setText("ADD MEDICINES");

        medicineIDLbl.setFont(new java.awt.Font("PT Sans", 1, 15)); // NOI18N
        medicineIDLbl.setText("Medicine ID");

        medicineIDTxtField.setFont(new java.awt.Font("PT Sans", 1, 15)); // NOI18N
        medicineIDTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineIDTxtFieldActionPerformed(evt);
            }
        });

        medicineNameLbl.setFont(new java.awt.Font("PT Sans", 1, 15)); // NOI18N
        medicineNameLbl.setText("Medicine Name");

        medicineNameTxtField.setFont(new java.awt.Font("PT Sans", 1, 15)); // NOI18N
        medicineNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineNameTxtFieldActionPerformed(evt);
            }
        });

        qtyLbl.setFont(new java.awt.Font("PT Sans", 1, 15)); // NOI18N
        qtyLbl.setText("Quantity");

        qtyTxtField.setFont(new java.awt.Font("PT Sans", 1, 15)); // NOI18N
        qtyTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyTxtFieldActionPerformed(evt);
            }
        });

        dosageLbl.setFont(new java.awt.Font("PT Sans", 1, 15)); // NOI18N
        dosageLbl.setText("Dosage");

        dosageTxtField.setFont(new java.awt.Font("PT Sans", 1, 15)); // NOI18N
        dosageTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosageTxtFieldActionPerformed(evt);
            }
        });

        commLbl.setFont(new java.awt.Font("PT Sans", 1, 15)); // NOI18N
        commLbl.setText("Community");

        commTxtField.setFont(new java.awt.Font("PT Sans", 1, 15)); // NOI18N
        commTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commTxtFieldActionPerformed(evt);
            }
        });

        storeIDLbl.setFont(new java.awt.Font("PT Sans", 1, 15)); // NOI18N
        storeIDLbl.setText("Store ID");

        storeIDTxtField.setFont(new java.awt.Font("PT Sans", 1, 15)); // NOI18N
        storeIDTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeIDTxtFieldActionPerformed(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("PT Sans", 1, 14)); // NOI18N
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        priceLbl.setFont(new java.awt.Font("PT Sans", 1, 15)); // NOI18N
        priceLbl.setText("Price / quantity");

        priceTxtField.setFont(new java.awt.Font("PT Sans", 1, 15)); // NOI18N
        priceTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtFieldActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("PT Sans", 1, 14)); // NOI18N
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(medicineTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(commLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(commTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dosageLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dosageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(qtyLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(qtyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(medicineIDLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(medicineIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(medicineNameLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(medicineNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(storeIDLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(storeIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(priceLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(priceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(medName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(medErrorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(qtyErrorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                            .addComponent(doseErrorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                            .addComponent(commErrorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(priceErrorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(backBtn)
                                .addGap(31, 31, 31)
                                .addComponent(addBtn)))))
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(medicineTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(medicineIDLbl)
                                    .addComponent(medicineIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(medErrorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(medicineNameLbl)
                                        .addComponent(medicineNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(medName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(qtyLbl)
                                    .addComponent(qtyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(qtyErrorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dosageLbl)
                            .addComponent(dosageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(doseErrorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceLbl)
                            .addComponent(priceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(commLbl)
                            .addComponent(commTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(priceErrorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(commErrorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(storeIDLbl)
                        .addComponent(storeIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void medicineIDTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineIDTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineIDTxtFieldActionPerformed

    private void medicineNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineNameTxtFieldActionPerformed

    private void qtyTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyTxtFieldActionPerformed

    private void dosageTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosageTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosageTxtFieldActionPerformed

    private void commTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commTxtFieldActionPerformed

    private void storeIDTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeIDTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storeIDTxtFieldActionPerformed

    private void priceTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtFieldActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String medicineId = medicineIDTxtField.getText();
        String name = medicineNameTxtField.getText();
        String quantity = qtyTxtField.getText();
        String dosage = dosageTxtField.getText();
        String price = priceTxtField.getText();
        String community = commTxtField.getText();
        String storeId = storeIDTxtField.getText();
        
        Inventory i = new Inventory();
        i.setMedicineID(medicineId);
        i.setMedicineName(name);
        i.setQuantity(Integer.parseInt(quantity));
        i.setDosage(dosage);
        i.setPrice(Float.parseFloat(price));
        i.setComm(community);
        i.setStoreID(storeId);
        
        InventoryDAOImp invDao = new InventoryDAOImp();
        invDao.add(i);
        JOptionPane.showMessageDialog(this, "Medicine details are added.");
        
        medicineIDTxtField.setText("");
        medicineNameTxtField.setText("");
        qtyTxtField.setText("");
        dosageTxtField.setText("");
        priceTxtField.setText("");
        commTxtField.setText("");
        storeIDTxtField.setText("");
    }//GEN-LAST:event_addBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        // TODO add your handling code here:
        InventoryProfile goToProfile = new InventoryProfile(jSplitPane);
        jSplitPane.setBottomComponent(goToProfile);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel commErrorLbl;
    private javax.swing.JLabel commLbl;
    private javax.swing.JTextField commTxtField;
    private javax.swing.JLabel dosageLbl;
    private javax.swing.JTextField dosageTxtField;
    private javax.swing.JLabel doseErrorLbl;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel medErrorLbl;
    private javax.swing.JLabel medName;
    private javax.swing.JLabel medicineIDLbl;
    private javax.swing.JTextField medicineIDTxtField;
    private javax.swing.JLabel medicineNameLbl;
    private javax.swing.JTextField medicineNameTxtField;
    private javax.swing.JLabel medicineTitle;
    private javax.swing.JLabel priceErrorLbl;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JTextField priceTxtField;
    private javax.swing.JLabel qtyErrorLbl;
    private javax.swing.JLabel qtyLbl;
    private javax.swing.JTextField qtyTxtField;
    private javax.swing.JLabel storeIDLbl;
    private javax.swing.JTextField storeIDTxtField;
    // End of variables declaration//GEN-END:variables
}
