/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import model.Patient.Patient;
import model.doctor.Doctor;
import model.inventory.Inventory;
import model.inventory.InventoryDAOImp;
import model.puchase.PurchaseDAOImp;

/**
 *
 * @author rodri
 */
public class DoctorPurchaseScreen extends javax.swing.JPanel {

    JSplitPane jSplitPane;
    Doctor doctor;
    Inventory inv;
    int quantity;
    String storeIdPurchased;
    float totalPrice;
    
        public DoctorPurchaseScreen(JSplitPane jSplitPane, Doctor doctor, Inventory inv, int quantity, String storeIdPurchchased) {
            
        this.jSplitPane = jSplitPane;
        this.doctor = doctor;
        this.inv = inv;
        this.quantity = quantity;
        this.storeIdPurchased = storeIdPurchchased;
        
         initComponents();
        totalPrice = 0;
        System.out.println("inventory Details in const"+ this.inv.getMedicineID()+ this.inv.getMedicineName());
        populateTable(this.inv);
        TotalTxtField.setText(String.valueOf(totalPrice));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkoutBtn1 = new javax.swing.JButton();
        purchaseTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        purchaseMedTable = new javax.swing.JTable();
        TotalLbl = new javax.swing.JLabel();
        TotalLbl1 = new javax.swing.JLabel();
        TotalTxtField = new javax.swing.JTextField();
        customerLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        docNameDisplay = new javax.swing.JLabel();
        contactNoLbl = new javax.swing.JLabel();
        contactDisplay = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        addressDisplay = new javax.swing.JLabel();

        setBackground(new java.awt.Color(160, 213, 229));

        checkoutBtn1.setFont(new java.awt.Font("PT Sans", 1, 14)); // NOI18N
        checkoutBtn1.setText("PLACE ORDER");
        checkoutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBtn1ActionPerformed(evt);
            }
        });

        purchaseTitle.setFont(new java.awt.Font("PT Sans", 1, 24)); // NOI18N
        purchaseTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purchaseTitle.setText("PURCHASE DETAILS");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/purchase.png"))); // NOI18N

        purchaseMedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "S.no", "Medicine Name", "Quantity", "Price / qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(purchaseMedTable);

        TotalLbl.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        TotalLbl.setText("Grand Total:");

        TotalLbl1.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        TotalLbl1.setText("Grand Total:");

        customerLbl.setFont(new java.awt.Font("PT Sans", 1, 18)); // NOI18N
        customerLbl.setText("Doctors Details");

        nameLbl.setFont(new java.awt.Font("PT Sans", 0, 14)); // NOI18N
        nameLbl.setText("Name:");

        docNameDisplay.setText("jLabel2");
        docNameDisplay.setText(this.doctor.getDocName());

        contactNoLbl.setFont(new java.awt.Font("PT Sans", 0, 14)); // NOI18N
        contactNoLbl.setText("Contact No:");

        contactDisplay.setText("jLabel3");
        contactDisplay.setText(this.doctor.getDocContact());

        addressLbl.setFont(new java.awt.Font("PT Sans", 0, 14)); // NOI18N
        addressLbl.setText("Address:");

        addressDisplay.setText("jLabel4");
        addressDisplay.setText(this.doctor.getDocAddress());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(purchaseTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 86, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(checkoutBtn1)
                                .addGap(345, 345, 345))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(contactNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(contactDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(580, 580, 580))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(addressDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TotalLbl1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TotalTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(customerLbl))
                                    .addGap(66, 66, 66)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(docNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(377, 377, 377)
                    .addComponent(TotalLbl)
                    .addContainerGap(377, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(purchaseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalLbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(docNameDisplay))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNoLbl)
                    .addComponent(contactDisplay))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLbl)
                    .addComponent(addressDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(checkoutBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(332, 332, 332)
                    .addComponent(TotalLbl)
                    .addContainerGap(332, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkoutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtn1ActionPerformed
        String email = doctor.getDocEmail();
        String medicineId = inv.getMedicineID();
        String storeId = storeIdPurchased;
        int quantity = this.quantity;
        String status = "Order placed";
        float totalPrice = this.totalPrice;
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
        LocalDateTime now = LocalDateTime.now();
        String updateTime = dtf.format(now);
        PurchaseDAOImp pDao = new PurchaseDAOImp();
        pDao.add(email, medicineId, storeId, quantity, status,updateTime , totalPrice);
        
        InventoryDAOImp inv = new InventoryDAOImp();
        inv.updateQuantity(medicineId, quantity);
        
        JOptionPane.showMessageDialog(this, "Thank you for placing an order.");
        
        DoctorStore docStore = new DoctorStore(jSplitPane);
        jSplitPane.setBottomComponent(docStore); 
        
// TODO add your handling code here:
    }//GEN-LAST:event_checkoutBtn1ActionPerformed
    
    
    public void populateTable(Inventory inv){
        System.out.println("in populate Table"+inv.getMedicineID()+ "--"+inv+ inv.getDosage()+inv.getPrice());
        
        this.totalPrice = this.quantity*inv.getPrice();
        System.out.println("in price in  Table"+ this.totalPrice);
        DefaultTableModel model = (DefaultTableModel) purchaseMedTable.getModel();
        System.out.println("in price in  Table -- 1");
        model.setRowCount(0);
        System.out.println("in price in  Table");
      
        int count=1;
        System.out.println("in count Table"+count);
//        Object[] row = new Object[6];
//        row[0]=count;
//        row[1]=inv;
//        row[2]=inv.getDosage();
//        row[3]= this.quantity;
//        row[4]=inv.getPrice();
//        row[5] = totalPrice;
        model.addRow(new Object[]{inv, inv.getDosage(), quantity, inv.getPrice(), totalPrice});
             
//        model.addRow(row);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotalLbl;
    private javax.swing.JLabel TotalLbl1;
    private javax.swing.JTextField TotalTxtField;
    private javax.swing.JLabel addressDisplay;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JButton checkoutBtn1;
    private javax.swing.JLabel contactDisplay;
    private javax.swing.JLabel contactNoLbl;
    private javax.swing.JLabel customerLbl;
    private javax.swing.JLabel docNameDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTable purchaseMedTable;
    private javax.swing.JLabel purchaseTitle;
    // End of variables declaration//GEN-END:variables
}
