/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nikethanann
 */
public class PatientProfile extends javax.swing.JPanel {

        JSplitPane splitPane;
        String storeName;
        String comm;

    public PatientProfile(JSplitPane splitPane, String storeName, String comm, String patientName) {
        initComponents();
        this.splitPane = splitPane;
        this.storeName = storeName;
        this.comm = comm;

        storeNameDisplay.setText(storeName);
        commDisplay.setText(comm);
        patientIDDisplay.setText(patientName);
        
        DefaultTableModel model = (DefaultTableModel) medicinesTable.getModel();
        System.out.println("In constructor PatientProfile");
        int sno = 1;
        String medicineName = "CVS";
        String dosage = "650mg";
        double price = 8.99;
        addRows(sno,medicineName,dosage,price);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientIDLbl = new javax.swing.JLabel();
        patientIDDisplay = new javax.swing.JLabel();
        storeNameDisplay = new javax.swing.JLabel();
        storeNameLbl = new javax.swing.JLabel();
        commDisplay = new javax.swing.JLabel();
        commLbl = new javax.swing.JLabel();
        loginTitle = new javax.swing.JLabel();
        ordersBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicinesTable = new javax.swing.JTable();
        checkoutBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(160, 213, 229));

        patientIDLbl.setFont(new java.awt.Font("PT Sans", 1, 18)); // NOI18N
        patientIDLbl.setText("Patient ID:");

        patientIDDisplay.setFont(new java.awt.Font("PT Sans", 1, 18)); // NOI18N
        patientIDDisplay.setText("jLabel2");

        storeNameDisplay.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        storeNameDisplay.setText("jLabel2");

        storeNameLbl.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        storeNameLbl.setText("Store Name:");

        commDisplay.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        commDisplay.setText("jLabel2");

        commLbl.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        commLbl.setText("Community:");

        loginTitle.setFont(new java.awt.Font("PT Sans", 1, 24)); // NOI18N
        loginTitle.setText("STORE DETAILS");

        ordersBtn.setFont(new java.awt.Font("PT Sans", 1, 14)); // NOI18N
        ordersBtn.setText("PAST ORDERS");

        medicinesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "S.no", "Medicine Name", "Dosage", "Quantity", "Price / qty", "Add"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(medicinesTable);

        checkoutBtn.setFont(new java.awt.Font("PT Sans", 1, 14)); // NOI18N
        checkoutBtn.setText("CHECKOUT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(storeNameLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(storeNameDisplay)
                                .addGap(31, 31, 31)
                                .addComponent(commLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(commDisplay))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(patientIDLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(patientIDDisplay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ordersBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(loginTitle)))
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(checkoutBtn)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(loginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientIDLbl)
                    .addComponent(patientIDDisplay)
                    .addComponent(ordersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storeNameLbl)
                    .addComponent(storeNameDisplay)
                    .addComponent(commLbl)
                    .addComponent(commDisplay))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(checkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JLabel commDisplay;
    private javax.swing.JLabel commLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JTable medicinesTable;
    private javax.swing.JButton ordersBtn;
    private javax.swing.JLabel patientIDDisplay;
    private javax.swing.JLabel patientIDLbl;
    private javax.swing.JLabel storeNameDisplay;
    private javax.swing.JLabel storeNameLbl;
    // End of variables declaration//GEN-END:variables

    private void addRows(int sno, String medicineName, String dosage, double price) {
        System.out.println("In method adddRows PatientProfile");
        DefaultTableModel model = (DefaultTableModel) medicinesTable.getModel();
        model.setRowCount(0);
        Object[] row = new Object[4];
        row[0] = sno;
        row[1] = medicineName;
        row[2] = dosage;
        row[3] = price;
        model.addRow(row);
    }
}
