/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;

/**
 *
 * @author rodri
 */
public class PharmacyAdminPanel extends javax.swing.JPanel {
 JSplitPane splitPane;
    /**
     * Creates new form PharmacyAdminPanel
     */
    public PharmacyAdminPanel(JSplitPane splitPane) {
        this.splitPane = splitPane;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ngoTbl = new javax.swing.JTable();
        findBtn = new javax.swing.JButton();
        contactLbl = new javax.swing.JLabel();
        contactLbl1 = new javax.swing.JLabel();
        ageTxtField = new javax.swing.JTextField();
        contactTextField = new javax.swing.JTextField();
        passwordLbl = new javax.swing.JLabel();
        passwordTxtField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        loginTitle = new javax.swing.JLabel();
        commSearchLbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ngoTbl1 = new javax.swing.JTable();
        createBtn = new javax.swing.JButton();
        nameTxtField = new javax.swing.JTextField();
        emailTxtField = new javax.swing.JTextField();
        nameLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        contactLbl2 = new javax.swing.JLabel();
        contactLbl3 = new javax.swing.JLabel();
        ageTxtField1 = new javax.swing.JTextField();
        contactTextField1 = new javax.swing.JTextField();
        passwordLbl1 = new javax.swing.JLabel();
        passwordTxtField1 = new javax.swing.JPasswordField();
        commTxtField = new javax.swing.JTextField();
        cityTxtField = new javax.swing.JTextField();
        nameLbl1 = new javax.swing.JLabel();
        cityLbl = new javax.swing.JLabel();
        emailLbl2 = new javax.swing.JLabel();
        storeTxtField = new javax.swing.JTextField();
        emailLbl3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        nmErrorLbl = new javax.swing.JLabel();
        emailErrorLbl = new javax.swing.JLabel();
        ageErrorLbl = new javax.swing.JLabel();
        contactErrorLbl = new javax.swing.JLabel();
        pwdErrorLbl = new javax.swing.JLabel();

        ngoTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NgoName", "Functionality", "Community", "City"
            }
        ));
        jScrollPane2.setViewportView(ngoTbl);

        findBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        findBtn.setText("FIND");
        findBtn.setMaximumSize(new java.awt.Dimension(74, 26));
        findBtn.setMinimumSize(new java.awt.Dimension(74, 26));
        findBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBtnActionPerformed(evt);
            }
        });

        contactLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contactLbl.setText("Contact:");

        contactLbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contactLbl1.setText("Age:");

        ageTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxtFieldActionPerformed(evt);
            }
        });
        ageTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ageTxtFieldKeyReleased(evt);
            }
        });

        contactTextField.setForeground(new java.awt.Color(204, 204, 204));
        contactTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTextFieldsignupBtnActionPerformed(evt);
            }
        });

        passwordLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordLbl.setText("Password:");

        passwordTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordTxtFieldKeyReleased(evt);
            }
        });

        setBackground(new java.awt.Color(160, 213, 229));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/first-aid-kit.png"))); // NOI18N

        loginTitle.setFont(new java.awt.Font("PT Sans", 1, 24)); // NOI18N
        loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTitle.setText("PHARMACY ADMIN");

        commSearchLbl.setFont(new java.awt.Font("PT Sans", 1, 14)); // NOI18N
        commSearchLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        commSearchLbl.setText("Create new Pharmasicts");

        ngoTbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Email", "Status", "Community", "City", "StoreName"
            }
        ));
        jScrollPane3.setViewportView(ngoTbl1);

        createBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        createBtn.setText("CREATE");
        createBtn.setMaximumSize(new java.awt.Dimension(74, 26));
        createBtn.setMinimumSize(new java.awt.Dimension(74, 26));
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        nameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtFieldActionPerformed(evt);
            }
        });
        nameTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTxtFieldKeyReleased(evt);
            }
        });

        emailTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtFieldActionPerformed(evt);
            }
        });
        emailTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTxtFieldKeyReleased(evt);
            }
        });

        nameLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameLbl.setText("Name:");

        emailLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailLbl.setText("Email:");

        contactLbl2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contactLbl2.setText("Contact:");

        contactLbl3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contactLbl3.setText("Age:");

        ageTxtField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxtField1ActionPerformed(evt);
            }
        });
        ageTxtField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ageTxtField1KeyReleased(evt);
            }
        });

        contactTextField1.setForeground(new java.awt.Color(204, 204, 204));
        contactTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTextField1signupBtnActionPerformed(evt);
            }
        });
        contactTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactTextField1KeyReleased(evt);
            }
        });

        passwordLbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordLbl1.setText("Password:");

        passwordTxtField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordTxtField1KeyReleased(evt);
            }
        });

        commTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commTxtFieldActionPerformed(evt);
            }
        });
        commTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                commTxtFieldKeyReleased(evt);
            }
        });

        cityTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTxtFieldActionPerformed(evt);
            }
        });
        cityTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cityTxtFieldKeyReleased(evt);
            }
        });

        nameLbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameLbl1.setText("Community:");

        cityLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cityLbl.setText("City:");

        emailLbl2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailLbl2.setText("storeName:");

        storeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeTxtFieldActionPerformed(evt);
            }
        });
        storeTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                storeTxtFieldKeyReleased(evt);
            }
        });

        emailLbl3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailLbl3.setText("Status:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        nmErrorLbl.setForeground(new java.awt.Color(255, 0, 0));

        emailErrorLbl.setForeground(new java.awt.Color(255, 0, 0));

        ageErrorLbl.setForeground(new java.awt.Color(255, 0, 0));

        contactErrorLbl.setForeground(new java.awt.Color(255, 0, 0));

        pwdErrorLbl.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loginTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                            .addComponent(commSearchLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(324, 324, 324))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(45, 45, 45)
                                                        .addComponent(emailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(45, 45, 45)
                                                        .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(contactLbl3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(contactLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(passwordLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGap(26, 26, 26))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(emailLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(passwordTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(contactTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ageTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(nmErrorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                                        .addComponent(emailErrorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(ageErrorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(contactErrorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGap(30, 30, 30)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(nameLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(commTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(cityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(27, 27, 27)
                                                            .addComponent(cityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(emailLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(storeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addComponent(pwdErrorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(29, 29, 29))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(commSearchLbl)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(commTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nameLbl1)
                        .addComponent(nmErrorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(nameLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl)
                    .addComponent(emailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityLbl)
                    .addComponent(cityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailErrorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailLbl2)
                            .addComponent(storeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactLbl3)
                            .addComponent(ageTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageErrorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactLbl2)
                            .addComponent(contactErrorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLbl1)
                            .addComponent(pwdErrorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLbl3))
                .addGap(27, 27, 27)
                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void findBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        String name = nameTxtField.getText();
        String email = emailTxtField.getText();
        String contact = contactTextField.getText();
        String community = commTxtField.getText();
        String age = ageTxtField.getText();
        String city=cityTxtField.getText(); 
        String storeName=storeTxtField.getText(); 

        //Need to add database interaction
        String password = String.valueOf(passwordTxtField.getPassword());
        if (name.isEmpty() || email.isEmpty() ||
                contact.isEmpty() || community.isEmpty() || community.isEmpty() || age.isEmpty() 
                || city.isEmpty() ||
                password.isEmpty() || jComboBox1.getSelectedItem().toString().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please Enter all fields");
        }
        else {
        
        }
        
    }//GEN-LAST:event_createBtnActionPerformed

    private void nameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtFieldActionPerformed
        // TODO add your handling code here:

        nameTxtField.setText("Enter UserName");
    }//GEN-LAST:event_nameTxtFieldActionPerformed

    private void nameTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTxtFieldKeyReleased
        // TODO add your handling code here:
        String namePattern="^[a-zA-Z]{0,30}$";
        Pattern pat=Pattern.compile(namePattern);
        Matcher match=pat.matcher(nameTxtField.getText());
        if (!match.matches()) {
            nmErrorLbl.setText("Naming is incorrect");
        }
        else {

            nmErrorLbl.setText(null);
        }
    }//GEN-LAST:event_nameTxtFieldKeyReleased

    private void emailTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtFieldActionPerformed
        // TODO add your handling code here:
        emailTxtField.setText("Enter Password");
    }//GEN-LAST:event_emailTxtFieldActionPerformed

    private void emailTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTxtFieldKeyReleased
        // TODO add your handling code here:

        String namePattern="^[a-zA-Z]{3,30}[@][a-zA-Z]{0,9}[.][a-zA-Z]{0,3}$";
        Pattern pat=Pattern.compile(namePattern);
        Matcher match=pat.matcher(emailTxtField.getText());
        if (!match.matches()) {
            emailErrorLbl.setText("emailId is incorrect");
        }
        else {
            emailErrorLbl.setText(null);
        }
    }//GEN-LAST:event_emailTxtFieldKeyReleased

    private void ageTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxtFieldActionPerformed

    private void ageTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTxtFieldKeyReleased
        // TODO add your handling code here:
//        String namePattern="^[0-9]{1,2}$";
//        Pattern pat=Pattern.compile(namePattern);
//        Matcher match=pat.matcher(ageTxtField.getText());
//        if (!match.matches()) {
//            ageLbl.setText("Age is incorrect!!Age should be int");
//        }
//        else {
//            ageLbl.setText(null);
//        }
    }//GEN-LAST:event_ageTxtFieldKeyReleased

    private void contactTextFieldsignupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTextFieldsignupBtnActionPerformed
     
    }//GEN-LAST:event_contactTextFieldsignupBtnActionPerformed

    private void ageTxtField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxtField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxtField1ActionPerformed

    private void ageTxtField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTxtField1KeyReleased
//        // TODO add your handling code here:
        String namePattern="^[0-9]{1,2}$";
        Pattern pat=Pattern.compile(namePattern);
        Matcher match=pat.matcher(ageTxtField.getText());
        if (!match.matches()) {
            ageErrorLbl.setText("Age is incorrect!!Age should be int");
        }
        else {
            ageErrorLbl.setText(null);
        }
    }//GEN-LAST:event_ageTxtField1KeyReleased

    private void contactTextField1signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTextField1signupBtnActionPerformed
     
    }//GEN-LAST:event_contactTextField1signupBtnActionPerformed

    private void passwordTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtFieldKeyReleased
        // TODO add your handling code here:

//        String namePattern="^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$";
//        Pattern pat=Pattern.compile(namePattern);
//        Matcher match=pat.matcher(passwordTxtField.getText());
//        if (!match.matches()) {
//            passLbl.setText("Invalid password!one uppercase,lowercase,special char and integer needed");
//        }
//        else {
//            passLbl.setText(null);
//        }
    }//GEN-LAST:event_passwordTxtFieldKeyReleased

    private void passwordTxtField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtField1KeyReleased
        // TODO add your handling code here:
        String namePattern="^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$";
        Pattern pat=Pattern.compile(namePattern);
        Matcher match=pat.matcher(passwordTxtField.getText());
        if (!match.matches()) {
            pwdErrorLbl.setText("Invalid password!one uppercase,lowercase,special char and integer needed");
        }
        else {
            pwdErrorLbl.setText(null);
        }
    }//GEN-LAST:event_passwordTxtField1KeyReleased

    private void commTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commTxtFieldActionPerformed

    private void commTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_commTxtFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_commTxtFieldKeyReleased

    private void cityTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTxtFieldActionPerformed

    private void cityTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityTxtFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTxtFieldKeyReleased

    private void storeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storeTxtFieldActionPerformed

    private void storeTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_storeTxtFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_storeTxtFieldKeyReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //coz if we dont checkout and click back the availblty shud b updated.

        AllAdmins allAdminPanel=new AllAdmins(splitPane);
        splitPane.setBottomComponent(allAdminPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void contactTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactTextField1KeyReleased
        // TODO add your handling code here:
         String namePattern="^[0-9]{9,9}$";
        Pattern pat=Pattern.compile(namePattern);
        Matcher match=pat.matcher(contactTextField.getText());
        if (!match.matches()) {
             contactErrorLbl.setText("Mobile number is incorrect");
        }
        else {
             contactErrorLbl.setText(null);
        }
    }//GEN-LAST:event_contactTextField1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageErrorLbl;
    private javax.swing.JTextField ageTxtField;
    private javax.swing.JTextField ageTxtField1;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel cityLbl;
    private javax.swing.JTextField cityTxtField;
    private javax.swing.JLabel commSearchLbl;
    private javax.swing.JTextField commTxtField;
    private javax.swing.JLabel contactErrorLbl;
    private javax.swing.JLabel contactLbl;
    private javax.swing.JLabel contactLbl1;
    private javax.swing.JLabel contactLbl2;
    private javax.swing.JLabel contactLbl3;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JTextField contactTextField1;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel emailErrorLbl;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel emailLbl2;
    private javax.swing.JLabel emailLbl3;
    private javax.swing.JTextField emailTxtField;
    private javax.swing.JButton findBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel nameLbl1;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JTable ngoTbl;
    private javax.swing.JTable ngoTbl1;
    private javax.swing.JLabel nmErrorLbl;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JLabel passwordLbl1;
    private javax.swing.JPasswordField passwordTxtField;
    private javax.swing.JPasswordField passwordTxtField1;
    private javax.swing.JLabel pwdErrorLbl;
    private javax.swing.JTextField storeTxtField;
    // End of variables declaration//GEN-END:variables
}
