/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import static com.itextpdf.text.Font.NORMAL;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JSplitPane;


/**
 *
 * @author rodri
 */
public class SalesPanel extends javax.swing.JPanel {
JSplitPane splitPane;
    /**
     * Creates new form SalesPanel
     */
    public SalesPanel(JSplitPane splitPane) {
        this.splitPane = splitPane;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loginTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        pdfBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(160, 213, 229));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/budget.png"))); // NOI18N

        loginTitle.setFont(new java.awt.Font("PT Sans", 1, 24)); // NOI18N
        loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTitle.setText("SALES");

        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"sam", "10", "100"},
                {"Drake", "30", "100"}
            },
            new String [] {
                "vendorName", "QtySold", "Price"
            }
        ));
        jScrollPane1.setViewportView(salesTable);

        pdfBtn.setFont(new java.awt.Font("PT Sans Caption", 1, 14)); // NOI18N
        pdfBtn.setText("GENERATE PDF");
        pdfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pdfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(pdfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pdfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfBtnActionPerformed
       String path="";
       JFileChooser j=new JFileChooser();
       j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
       int x=j.showSaveDialog(this);
       if (x==JFileChooser.APPROVE_OPTION) {
           path=j.getSelectedFile().getPath();
           
       }
       
       //Document doc=new Document();
       
       Document doc=new Document();
       try {
       PdfWriter.getInstance(doc,new FileOutputStream(path+"phramacysales.pdf"));
       doc.open();
       PdfPTable tbl=new PdfPTable(3);
       tbl.addCell("VendorName");
       tbl.addCell("QtySold");
       tbl.addCell("Price");
         
         for (int i=0;i<salesTable.getRowCount();i++) {
             
             System.out.println("data"+salesTable.getRowCount());
             System.out.println("data1"+salesTable.getValueAt(i, 0).toString());
             String name=salesTable.getValueAt(i, 0).toString();
             String soldQty=salesTable.getValueAt(i, 1).toString();
             String amount=salesTable.getValueAt(i, 2).toString();
             
             tbl.addCell(name);
             tbl.addCell(soldQty);
             tbl.addCell(amount);
             
         }
         
         doc.add(tbl);
       
       }
       catch(FileNotFoundException ex) {
          System.out.println("File error");
           
       }
       catch(DocumentException ex) {
          
           System.out.println("Doc error");
       }
       
       doc.close();
       
        // TODO add your handling code here:
    }//GEN-LAST:event_pdfBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JButton pdfBtn;
    private javax.swing.JTable salesTable;
    // End of variables declaration//GEN-END:variables
}
